version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://walking-rabbit-db.cj24wem202yj.us-east-1.rds.amazonaws.com:3306/walking-rabbit-db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: user123!
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    restart: unless-stopped